### ISSUE TITLE
Issue with fail2ban on web client

### ISSUE THREAD

**Issue by killmasta93** [charles-josiah/confz#1]
Hi, 
Currently trying to setup with the fail2ban for zimbra for the web interface, i checked the log
in the /opt/zimbra/log/audit.log

`2020-01-01 19:39:13,792 WARN  [qtp510063093-564://localhost:8080/service/soap/AuthRequest] [name=sistemas@mydomain.co;oip=192.168.3.100;ua=zclient/8.8.15_GA_3888;soapId=ff6f83b;] security - cmd=Auth; account=sistemas@mydomain.co; protocol=soap; error=authentication failed for [sistemas], invalid password;
`
this is my jail.local

https://pastebin.com/PrBhfpka

and this is my zimbra.conf in filter.d

https://pastebin.com/EUU90ukC

Thank you

**Comment by charles-josiah** [comment]
Helo, i am sorry that i have only to see your message. 
I see that my filters will work, becasuse i search the oip, the oip is the external address to block.
But i dont understant what is you question. 
You can send me a email, charles.alandt at gmail dot com, if you wanna some help.

**Comment by charles-josiah** [comment]
I have tested, i beleave you need to make this steps.
https://wiki.zimbra.com/wiki/Log_Files 
section: Logging the Originating IP

**Comment by killmasta93** [comment]
Thank you that did the trick on the log files
